### ISSUE TITLE
hi,怎么支持直接回复特定消息啊

### ISSUE THREAD

**Issue by haiy** [howie6879/examiner#3]
hi,大兄弟，我想看到某个消息后自动回复，但是找了一圈没找到什么比较好的接口，请问你有什么思路么

**Comment by howie6879** [comment]
你回哪端的信息都不说，我怎么回你。

**Comment by haiy** [comment]
具体场景是这样的，在mac上，我想能够自动回复微信特定人发过来的消息，看到你这个工具比较有意思就想尝试下

**Comment by howie6879** [comment]
这个只能监听
