### ISSUE TITLE
windows上的消息通知db存储路径如何获取呢

### ISSUE THREAD

**Issue by No1Jie** [howie6879/examiner#5]
测试了下在mac上是可以的，这个应用使用场景一般是界面化的操作系统，windows上的消息存储路径不知如何获取～研究了没找到好方法，望赐教

**Comment by howie6879** [comment]
windows我也没办法，非界面化的也行，只要搞清楚通知中心地址就行

**Comment by No1Jie** [comment]
刚找到了windows下的消息通知存放路径：<系统盘>\Users\<用户名>\AppData\Local\Microsoft\Windows\Notifications路径下看到一个命名为wpndatabase.db的数据库文件

有个比较麻烦的是存放安装包的info.plist路径不固定，需要人为固定后也可

**Comment by howie6879** [comment]
你win哪个版本啊，如果可用的话，可以考虑来个pr~~

No1Jie <notifications@github.com> 于2020年12月22日周二 上午11:10写道：

**Comment by No1Jie** [comment]
windows 10，刚看了下wpndatabase.db这个数据库，数据不是最新的，再看看

**Comment by howie6879** [comment]
> windows 10，刚看了下wpndatabase.db这个数据库，数据不是最新的，再看看

有什么进展吗？
